# Use the official gcc image
image: gcc

stages:
    - build

before_script:
    # Install build dependencies
    - apt-get update && apt-get -y install cmake freeglut3 freeglut3-dev libglew-dev libwxgtk3.0-dev
    - gcc --version

MoA:
    # Build the application
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make